version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    # Uncomment and configure if using PostgreSQL
    # depends_on:
    #   - postgres

  # Uncomment if you want to use PostgreSQL instead of in-memory storage
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: velvotek_status
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: your_password_here
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: